version: '3.9'

services:

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    environment:
      NGINX_LOGIN: '${NGINX_LOGIN}'
      NGINX_PASS: '${NGINX_PASS}'
    volumes:
     - wp_data:/var/lib/wordpress
    ports:
     - '${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}'
    restart: always
    networks:
     - inception


  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_LOGIN: '${MARIADB_ROOT_LOGIN}'
      MARIADB_ROOT_PASS: '${MARIADB_ROOT_PASS}'
      MARIADB_MY_LOGIN: '${MARIADB_MY_LOGIN}'
      MARIADB_MY_PASS: '${MARIADB_MY_PASS}'
    ports:
      - '${MARIADB_HOST_PORT}:${MARIADB_CONTAINER_PORT}'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress-container
#    environment:
    volumes:
      - wp_data:/var/lib/wordpress
    restart: always
    networks:
      - inception

networks:
  inception:

volumes:
  db_data:
    name: db_data

  wp_data:
    name: wp_data
    driver: local
    driver_opts:

